# Generated by Django 5.2.5 on 2025-08-24 08:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_dish_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo'),
        ),
    ]
