# Generated by Django 5.2.5 on 2025-08-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0003_alter_dish_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='dish_type',
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_type',
            field=models.ManyToManyField(to='dish.dishtype'),
        ),
    ]
