# Generated by Django 5.2.5 on 2025-08-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dish", "0004_remove_dish_dish_type_dish_dish_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={
                "ordering": ["name"],
                "verbose_name": "Dish",
                "verbose_name_plural": "Dishes",
            },
        ),
        migrations.AlterModelOptions(
            name="dishtype",
            options={
                "ordering": ["name"],
                "verbose_name": "Dish Type",
                "verbose_name_plural": "Dish Types",
            },
        ),
        migrations.AlterModelTable(
            name="dish",
            table="dish",
        ),
        migrations.AlterModelTable(
            name="dishtype",
            table="dish_type",
        ),
    ]
