# Generated by Django 5.2.5 on 2025-08-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingredient", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "ordering": ["name"],
                "verbose_name": "Ingredient",
                "verbose_name_plural": "Ingredients",
            },
        ),
        migrations.AlterModelTable(
            name="ingredient",
            table="ingredient",
        ),
    ]
