# Generated by Django 5.2.5 on 2025-08-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cook", "0002_cook_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={
                "ordering": ["username"],
                "verbose_name": "Cook",
                "verbose_name_plural": "Cooks",
            },
        ),
        migrations.AlterModelTable(
            name="cook",
            table="cook",
        ),
    ]
